Traceback (most recent call last):
  File "/Users/domfj/Library/Caches/pypoetry/virtualenvs/sf-ff-service-KkBImDKy-py3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/domfj/Library/Caches/pypoetry/virtualenvs/sf-ff-service-KkBImDKy-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/domfj/Library/Caches/pypoetry/virtualenvs/sf-ff-service-KkBImDKy-py3.11/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/domfj/Library/Caches/pypoetry/virtualenvs/sf-ff-service-KkBImDKy-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/domfj/Library/Caches/pypoetry/virtualenvs/sf-ff-service-KkBImDKy-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/domfj/Library/Caches/pypoetry/virtualenvs/sf-ff-service-KkBImDKy-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import plotly.io as pio
pio.renderers.default = 'plotly_html'
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mio[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpio[39;00m
[0;32m----> 2[0m [43mpio[49m[38;5;241;43m.[39;49m[43mrenderers[49m[38;5;241;43m.[39;49m[43mdefault[49m [38;5;241m=[39m [38;5;124m'[39m[38;5;124mplotly_html[39m[38;5;124m'[39m

File [0;32m~/Library/Caches/pypoetry/virtualenvs/sf-ff-service-KkBImDKy-py3.11/lib/python3.11/site-packages/plotly/io/_renderers.py:150[0m, in [0;36mRenderersConfig.default[0;34m(self, value)[0m
[1;32m    147[0m     [38;5;28;01mreturn[39;00m
[1;32m    149[0m [38;5;66;03m# Store defaults name and list of renderer(s)[39;00m
[0;32m--> 150[0m renderer_names [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_validate_coerce_renderers[49m[43m([49m[43mvalue[49m[43m)[49m
[1;32m    151[0m [38;5;28mself[39m[38;5;241m.[39m_default_name [38;5;241m=[39m value
[1;32m    152[0m [38;5;28mself[39m[38;5;241m.[39m_default_renderers [38;5;241m=[39m [[38;5;28mself[39m[name] [38;5;28;01mfor[39;00m name [38;5;129;01min[39;00m renderer_names]

File [0;32m~/Library/Caches/pypoetry/virtualenvs/sf-ff-service-KkBImDKy-py3.11/lib/python3.11/site-packages/plotly/io/_renderers.py:217[0m, in [0;36mRenderersConfig._validate_coerce_renderers[0;34m(self, renderers_string)[0m
[1;32m    215[0m         invalid [38;5;241m=[39m [name [38;5;28;01mfor[39;00m name [38;5;129;01min[39;00m renderer_names [38;5;28;01mif[39;00m name [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [38;5;28mself[39m]
[1;32m    216[0m         [38;5;28;01mif[39;00m invalid:
[0;32m--> 217[0m             [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    218[0m [38;5;250m                [39m[38;5;124;03m"""[39;00m
[1;32m    219[0m [38;5;124;03mInvalid named renderer(s) received: {}"""[39;00m[38;5;241m.[39mformat(
[1;32m    220[0m                     [38;5;28mstr[39m(invalid)
[1;32m    221[0m                 )
[1;32m    222[0m             )
[1;32m    224[0m         [38;5;28;01mreturn[39;00m renderer_names

[0;31mValueError[0m: 
Invalid named renderer(s) received: ['plotly_html']

